# HIDDEN LAYER 2

In [4]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)



Epoch 0, Loss: 0.2607742187992384
Epoch 1000, Loss: 0.20304150819181932
Epoch 2000, Loss: 0.15316027967459567
Epoch 3000, Loss: 0.048021864594492786
Epoch 4000, Loss: 0.016366736695772145
Epoch 5000, Loss: 0.008804528829924267
Epoch 6000, Loss: 0.005818919270616762
Epoch 7000, Loss: 0.004280776685442453
Epoch 8000, Loss: 0.003358824916288804
Epoch 4000, Loss: 0.016366736695772145
Epoch 5000, Loss: 0.008804528829924267
Epoch 6000, Loss: 0.005818919270616762
Epoch 7000, Loss: 0.004280776685442453
Epoch 8000, Loss: 0.003358824916288804
Epoch 9000, Loss: 0.0027503127057597223
Prediksi:
[[0.04215844]
 [0.94993062]
 [0.94974632]
 [0.04976118]]
Epoch 9000, Loss: 0.0027503127057597223
Prediksi:
[[0.04215844]
 [0.94993062]
 [0.94974632]
 [0.04976118]]


# HIDDEN LAYER 3

In [5]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)



Epoch 0, Loss: 0.28860556873898646
Epoch 1000, Loss: 0.2377929324533501
Epoch 2000, Loss: 0.1917670026380035
Epoch 3000, Loss: 0.15698936460144525
Epoch 4000, Loss: 0.1423907639194747
Epoch 4000, Loss: 0.1423907639194747
Epoch 5000, Loss: 0.13615210068837907
Epoch 6000, Loss: 0.1329892648777887
Epoch 7000, Loss: 0.1311448330724763
Epoch 8000, Loss: 0.12995730084841786
Epoch 9000, Loss: 0.1291366459192758
Prediksi:
[[0.04531227]
 [0.94481   ]
 [0.49744008]
 [0.50645121]]
Epoch 5000, Loss: 0.13615210068837907
Epoch 6000, Loss: 0.1329892648777887
Epoch 7000, Loss: 0.1311448330724763
Epoch 8000, Loss: 0.12995730084841786
Epoch 9000, Loss: 0.1291366459192758
Prediksi:
[[0.04531227]
 [0.94481   ]
 [0.49744008]
 [0.50645121]]


# HIDDEN LAYER 2 DENGAN ReLU

In [6]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)


Epoch 0, Loss: 0.20255121117473107
Epoch 1000, Loss: 0.1261642706267239
Epoch 2000, Loss: 0.12539290629924466
Epoch 3000, Loss: 0.12522119461011463
Epoch 4000, Loss: 0.1251582067258604
Epoch 5000, Loss: 0.1251210869046204
Epoch 6000, Loss: 0.12510232451916858
Epoch 7000, Loss: 0.12508118155304035
Epoch 8000, Loss: 0.1250701603095976
Epoch 9000, Loss: 0.12506020278242244
Prediksi:
[[0.49988271]
 [0.99113132]
 [0.49988271]
 [0.01162853]]
Epoch 6000, Loss: 0.12510232451916858
Epoch 7000, Loss: 0.12508118155304035
Epoch 8000, Loss: 0.1250701603095976
Epoch 9000, Loss: 0.12506020278242244
Prediksi:
[[0.49988271]
 [0.99113132]
 [0.49988271]
 [0.01162853]]


# HIDDEN LAYER 3 DENGAN ReLU

In [7]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)


Epoch 0, Loss: 0.3442930083158279
Epoch 1000, Loss: 0.1259782932192119
Epoch 2000, Loss: 0.12538697667070073
Epoch 3000, Loss: 0.12521187136046114
Epoch 4000, Loss: 0.12514594715577432
Epoch 5000, Loss: 0.12511934559901172
Epoch 2000, Loss: 0.12538697667070073
Epoch 3000, Loss: 0.12521187136046114
Epoch 4000, Loss: 0.12514594715577432
Epoch 5000, Loss: 0.12511934559901172
Epoch 6000, Loss: 0.1250899399832436
Epoch 7000, Loss: 0.125074827382527
Epoch 6000, Loss: 0.1250899399832436
Epoch 7000, Loss: 0.125074827382527
Epoch 8000, Loss: 0.12506480514872712
Epoch 9000, Loss: 0.12506091021696158
Prediksi:
[[0.4999614 ]
 [0.4999614 ]
 [0.99077938]
 [0.0101288 ]]
Epoch 8000, Loss: 0.12506480514872712
Epoch 9000, Loss: 0.12506091021696158
Prediksi:
[[0.4999614 ]
 [0.4999614 ]
 [0.99077938]
 [0.0101288 ]]


# PERBANDINGAN HASIL

## Perbandingan Fungsi Aktivasi

**Sigmoid:**
- Fungsi aktivasi klasik yang menghasilkan output antara 0 dan 1
- Cocok untuk output layer dalam klasifikasi biner
- Memiliki masalah vanishing gradient pada layer yang dalam

**ReLU (Rectified Linear Unit):**
- Fungsi aktivasi yang mengembalikan 0 untuk nilai negatif dan x untuk nilai positif
- Lebih cepat dalam training dan mengurangi masalah vanishing gradient
- Cocok untuk hidden layer

## Perbandingan Jumlah Neuron

**2 Neuron Hidden Layer:**
- Arsitektur minimal untuk menyelesaikan masalah XOR
- Training lebih cepat tetapi mungkin kurang fleksibel

**3 Neuron Hidden Layer:**
- Memberikan lebih banyak kapasitas untuk mempelajari pola
- Dapat menghasilkan representasi yang lebih kompleks